### ISSUE TITLE
3d yönlendirme?

### ISSUE THREAD

**Issue by necoakdogan** [ofke-yazilim/parampos-v2#2]
Merhaba,

Öncelikle repo için minnetlerimizi sunmaktayız işimizi kolaylaştırdınız.Sorunsuzca test işlemini yapabiliyoruz ancak bir konu hakkında bilginize ihtiyacımız var. 3d ödeme yönlendirmesini direk olarak yaptığımızda hata alıyoruz. Öncelikle ekrana link yazdırıp o linkle tıklandıktan sonra 3d şifre ekranına gidebiliyoruz. Bu olay sadece test modunda mı geçerli yoksa prod moduna aldığımızda da illaki 3d sayfasına gidilmesi için buton koymak zorunda mıyız? Bilgilendirebilirseniz çok seviniriz.

İyi çalışmalar dileriz.

**Comment by ofke-yazilim** [comment]
Prod ortam üzerinde denemedim daha önce. Fakat yönlendirme olsa bile siz onu jquery kullanarak sayfada görünmeden yönlendirebilirsiniz.
